### ISSUE TITLE
Possible to pass variables from processingjs to meteor with this configuration?

### ISSUE THREAD

**Issue by davidkneely** [bgrayburn/meteor-processing-js-test#1]
I'm making a meteor app that uses processingjs. Does this configuration allow for passing mouse positions in processingjs to meteor?

**Comment by bgrayburn** [comment]
Hey @davidkneely , thanks for your question. I would look at the [Pomax Guide] (http://processingjs.org/articles/PomaxGuide.html) to do what you've described. Although my sincere suggestion is you use P5.js instead of processing.js which will make your life much easier for what you just described.

**Comment by davidkneely** [comment]
@bgrayburn Thanks for the quick answer and the link. This is exactly what I was looking for :+1:

**Comment by bgrayburn** [comment]
no problem! best of luck
